### ISSUE TITLE
Injured / Suspended players process fail due to team null

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#141]
Since today (19/12), process fail with:

```
java.lang.UnsupportedOperationException: The team can't be null here, implement problem (should be filled before)
	at org.blondin.mpg.out.model.Player.getTeam(Player.java:54)
	at org.blondin.mpg.out.InjuredSuspendedEquipeActuClient.getPlayer(InjuredSuspendedEquipeActuClient.java:112)
	at org.blondin.mpg.out.InjuredSuspendedWrapperClient.getPlayer(InjuredSuspendedWrapperClient.java:47)
	at org.blondin.mpg.Main.removeOutPlayers(Main.java:328)
	at org.blondin.mpg.Main.processGames(Main.java:174)
	at org.blondin.mpg.Main.processLeague(Main.java:111)
	at org.blondin.mpg.Main.process(Main.java:82)
	at org.blondin.mpg.Main.main(Main.java:67)

```

**Root cause**: Team name is not displayed on EquipeActu Website.

Sample from: https://www.equipeactu.fr/blessures-et-suspensions/fodbold/france/ligue-1

![image](https://user-images.githubusercontent.com/2912441/71199778-f9d2c500-2296-11ea-829a-5825df25c58b.png)

Mail sent to EquipeActu ... but if not fixed soon, solution should be found ASAP.

**Comment by axel3rd** [comment]
Reopen because with current implementation, a player in a team which can be parsed (no team name, blank logo) is considered in the previous team: 

![image](https://user-images.githubusercontent.com/2912441/71310403-02043f00-2414-11ea-8a97-01ef52e6f21d.png)

=> A team "null" should be considered in the injury/suspended search
