### ISSUE TITLE
NPE on players stats data

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#151]
```
Exception in thread "main" java.lang.NullPointerException
        at java.util.Date.getMillisOf(Date.java:958)
        at java.util.Date.before(Date.java:917)
        at org.blondin.mpg.stats.MpgStatsClient.getStats(MpgStatsClient.java:40)
        at org.blondin.mpg.Main.getCurrentDay(Main.java:401)
        at org.blondin.mpg.Main.calculateEfficiency(Main.java:365)
        at org.blondin.mpg.Main.processGames(Main.java:170)
        at org.blondin.mpg.Main.processLeague(Main.java:111)
        at org.blondin.mpg.Main.process(Main.java:82)
        at org.blondin.mpg.Main.main(Main.java:67)
```

**Comment by axel3rd** [comment]
The root cause is that Player statistics build date (https://api.mlnstats.com/builds) seems invalid:

```
{
  "3": "2020-01-06T04:30:22.934Z",
  "5": "2020-01-06T04:31:09.290Z"
}
```

**Comment by axel3rd** [comment]
Hi @LittleLama, 

> The root cause is that Player statistics build date (https://api.mlnstats.com/builds) seems invalid:

Sorry to bother you with that, but (following #134) is it normal that que https://api.mlnstats.com/builds endpoint contains only date for **Liga** & **SerieA** ?

```
{
  "3": "2020-01-06T04:30:22.934Z",
  "5": "2020-01-06T04:31:09.290Z"
}
```

This endpoint which indicates when league data should be updated (https://api.mlnstats.com/leagues/[LeagueName]) is now deprecated ?

Thanks in advance.
Best regards

**Comment by LittleLama** [comment]
Uhm, that bug is weird, I'm going to check that.

Le lun. 6 janv. 2020 à 11:23, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> Uhm, that bug is weird, I'm going to check that.

@LittleLama Many thx. It is now better, only id "4" is missing now 😁.
