### ISSUE TITLE
Fail with "Connection reset"

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#160]
Some *Connection Reset* could occur :

```
Call URL: https://api.monpetitgazon.com/user/signIn (cache duration ms: -1)
Call URL time elaps ms: 14801
Call URL: https://api.monpetitgazon.com/user/dashboard (cache duration ms: -1)
Call URL time elaps ms: 804
Exception in thread "main" javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
        ...
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:135)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:82)
        at org.blondin.mpg.root.MpgClient.getDashboard(MpgClient.java:73)
        at org.blondin.mpg.Main.process(Main.java:72)
        at org.blondin.mpg.Main.main(Main.java:68)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        ...
```

It is strange because it is on Dashboard (SignIn was OK), an only when executed on Linux in Crontab.

**Comment by axel3rd** [comment]
https://github.com/axel3rd/mpg-coach-bot/blob/14fba959512b65532ae5836c76a876c5937111b5/src/main/java/org/blondin/mpg/root/MpgClient.java#L32

Now this is **6.2.0**, and header `client-version` is **present in all MPG requests** (not only signin) => Try this update & fix.

**Comment by axel3rd** [comment]
> client-version is present in all MPG requests (not only signin)

It is already implemented, current behavior 😬

**Comment by axel3rd** [comment]
Problem occurs on *signin* in addition:

```
Call URL: https://api.monpetitgazon.com/user/signIn (cache duration ms: -1)
Call URL time elaps ms: 15814
Exception in thread "main" javax.ws.rs.client.ResponseProcessingException: java.net.SocketException: Connection reset
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:657)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:648)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:648)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:618)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:423)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:329)
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:137)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:98)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:90)
        at org.blondin.mpg.root.MpgClient.signIn(MpgClient.java:93)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:51)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:43)
```

**Comment by axel3rd** [comment]
> only when executed on Linux in Crontab

No, *Connection Reset* problem occurs on Windows via IDE execution.

**Comment by axel3rd** [comment]
Seems OK, last logs from my crontab:

```
Call URL: https://api.monpetitgazon.com/user/signIn (cache duration ms: -1)
Call URL time elaps ms: 16048
Call URL: https://api.monpetitgazon.com/user/dashboard (cache duration ms: -1)
Retrying ('java.net.SocketException: Connection reset' on 'https://api.monpetitgazon.com/user/dashboard')...
Call URL time elaps ms: 6708
```

*signIn* quite long ... strange. Waiting futur leagues restart for real checks ...
