### ISSUE TITLE
Injured & Suspended players: Switch from EquipeActu to SportsGambler

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#169]
**Initially considered as a bug, this issue is finally updated as an improvement (see below).**

----

**Describe the bug**

```
Exception in thread "main" java.lang.UnsupportedOperationException: No teams have been found, parsing problem
        at org.blondin.mpg.out.InjuredSuspendedEquipeActuClient.getPlayers(InjuredSuspendedEquipeActuClient.java:209)
        at org.blondin.mpg.out.InjuredSuspendedEquipeActuClient.getPlayers(InjuredSuspendedEquipeActuClient.java:178)
        at org.blondin.mpg.out.InjuredSuspendedEquipeActuClient.getPlayer(InjuredSuspendedEquipeActuClient.java:157)
        at org.blondin.mpg.out.InjuredSuspendedWrapperClient.getPlayer(InjuredSuspendedWrapperClient.java:47)
        at org.blondin.mpg.Main.removeOutPlayers(Main.java:337)
        at org.blondin.mpg.Main.processGames(Main.java:178)
        at org.blondin.mpg.Main.processLeague(Main.java:115)
        at org.blondin.mpg.Main.process(Main.java:83)
        at org.blondin.mpg.Main.main(Main.java:68)
```

**Root cause**

The injured & suspended players URL has change:
- From https://www.equipeactu.fr/blessures-et-suspensions/
- To https://www.equipeactu.fr/injuries-suspensions/

**Comment by axel3rd** [comment]
https://www.equipeactu.fr/injuries-suspensions could return HTTP 404 .... strange behavior it depends of time 😢.

**Comment by axel3rd** [comment]
Perhaps **transfermarkt** can be used, sample for L1: https://www.transfermarkt.fr/ligue-1/verletztespieler/wettbewerb/FR1/plus/1

Check if all championships are here, and if players injured/suspended are the same as equipeactu.

**Comment by axel3rd** [comment]
> Perhaps transfermarkt can be used, sample for L1: https://www.transfermarkt.fr/ligue-1/verletztespieler/wettbewerb/FR1/plus/1
> Check if all championships are here, and if players injured/suspended are the same as equipeactu.

Not a good idea, because for L1;
- equipeactu: **87 players** (injured / suspended)
- transfermarkt : **31 players** (injured / suspended)

**Comment by axel3rd** [comment]
Best website seems to be [sportsgambler.](https://www.sportsgambler.com/football/injuries-suspensions/):
- https://www.sportsgambler.com/football/injuries-suspensions/france-ligue-1/
- https://www.sportsgambler.com/football/injuries-suspensions/england-premier-league/
- https://www.sportsgambler.com/football/injuries-suspensions/italy-serie-a/

Type: 
- `+` : Injured => red
- `?` : Doubt => Orange
- `[red card]` => red
