### ISSUE TITLE
Forbidden URL on MPG API

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#174]
**Describe the bug**

Since this week, and when some websites seems slow, the last MPG league update throws:

```Updating team ...
Exception in thread "main" org.blondin.mpg.root.exception.UrlForbiddenException: Forbidden URL: https://api.monpetitgazon.com
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:157)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:118)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:114)
        at org.blondin.mpg.root.MpgClient.updateCoach(MpgClient.java:97)
        at org.blondin.mpg.Main.updateTeamWithRetry(Main.java:237)
        at org.blondin.mpg.Main.processGames(Main.java:189)
        at org.blondin.mpg.Main.processLeague(Main.java:115)
        at org.blondin.mpg.Main.process(Main.java:83)
        at org.blondin.mpg.Main.main(Main.java:68)
```

Should be troubleshooted, and token scope return analysed, currently to time revocation is implemented.

**Comment by axel3rd** [comment]
This problem is really random ... not appears again
