### ISSUE TITLE
Sportsgambler new URLs and HTML content (some Crashes on parsing)

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#178]
```
Exception in thread "main" java.lang.NullPointerException
        at org.blondin.mpg.out.InjuredSuspendedSportsGamblerClient.getPlayers(InjuredSuspendedSportsGamblerClient.java:100)
        at org.blondin.mpg.out.AbstractInjuredSuspendedNotL2.getPlayers(AbstractInjuredSuspendedNotL2.java:96)
        at org.blondin.mpg.out.AbstractInjuredSuspendedNotL2.getPlayer(AbstractInjuredSuspendedNotL2.java:79)
        at org.blondin.mpg.out.AbstractInjuredSuspendedNotL2.getPlayer(AbstractInjuredSuspendedNotL2.java:35)
        at org.blondin.mpg.out.InjuredSuspendedWrapperClient.getPlayer(InjuredSuspendedWrapperClient.java:59)
        at org.blondin.mpg.Main.removeOutPlayers(Main.java:337)
        at org.blondin.mpg.Main.processGames(Main.java:178)
        at org.blondin.mpg.Main.processLeague(Main.java:115)
        at org.blondin.mpg.Main.process(Main.java:83)
        at org.blondin.mpg.Main.main(Main.java:68)
```

File:  [sportsgambler.ligue-1.20210223.html.zip](https://github.com/axel3rd/mpg-coach-bot/files/6032222/sportsgambler.ligue-1.20210223.html.zip)

**Comment by axel3rd** [comment]
The HTML content has change, and the URLs to injuries:
- From https://www.sportsgambler.com/football/injuries-suspensions/
- To https://www.sportsgambler.com/injuries/football/
