### ISSUE TITLE
Crash on "Transactions proposal" and fix budget when some players proposition is existing

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#187]
```
Updating team ...

Transactions proposal ...
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.blondin.mpg.Main.writeTransactionsProposal(Main.java:262)
        at org.blondin.mpg.Main.processGames(Main.java:208)
        at org.blondin.mpg.Main.processLeague(Main.java:115)
        at org.blondin.mpg.Main.process(Main.java:83)
        at org.blondin.mpg.Main.main(Main.java:68)
```

**Comment by axel3rd** [comment]
The root cause is when team has no Goalkeepers

**Comment by axel3rd** [comment]
In addition, the proposed budget should take into account the current proposals on some players.
