### ISSUE TITLE
New app/website support

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#191]
With new app/website (since **July, 19**), the current signin process throws: 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 404 Not Found / Content: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.0</center>
</body>
</html>

        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:169)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:119)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:111)
        at org.blondin.mpg.root.MpgClient.signIn(MpgClient.java:91)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:49)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:43)
        at org.blondin.mpg.Main.main(Main.java:65)
```

New website should be analysed, to see if can be supported (in the past, MPG team has announced that website will be disengaged).

**Comment by axel3rd** [comment]
New website doesn't provide any way to manage your leagues/teams ; only mercato preparation.

The only solution is to analyse Mobile application traffic (ex: Android), less easy 😢.

**Comment by axel3rd** [comment]
New root endpoint: `https://api.mpg.football`

| Feature | Web | Mobile |
|---|---|---|
| login | `GET /user/signIn` | `GET /user/sign-in` | 
| home | `GET /user/dashboard` | `GET /dashboard/leagues` | 
| coach | `GET /league/[yourLeagueId]/coach` | `/division/mpg_division_[yourLeagueId]_3_1/coach` | 
| transfer | `GET /league/[yourLeagueId]/transfer/buy` | `/division/mpg_division_[yourLeagueId]_3_1/available-players` | 
| mercato | `GET /league/[yourLeagueId]/mercato` | (should wait the use case) | 

**WARN**:
- The `3_1` come from `divisionId` is *"home"*
-  `email` updated to `login` in JSon content

The Coas update is `PUT /match-team-formation/mpg_match_team_formation_MLEFEX6G_3_1_2_2_2` with content:

```
{"composition":"343","playersOnPitch":{"1":"mpg_championship_player_220359","2":"mpg_championship_player_209171","3":"mpg_championship_player_245485","4":"mpg_championship_player_235708","5":"mpg_championship_player_167454","6":"mpg_championship_player_92353","7":"mpg_championship_player_204405","8":"mpg_championship_player_177449","9":"mpg_championship_player_228313","10":"mpg_championship_player_511596","11":"mpg_championship_player_423064","12":"mpg_championship_player_512711","13":"mpg_championship_player_509285","14":"mpg_championship_player_454964","15":"mpg_championship_player_437503","16":"mpg_championship_player_173242","17":"mpg_championship_player_149035","18":"mpg_championship_player_102724"},"tacticalSubs":[{"rating":4,"starterId":"mpg_championship_player_511596","subId":"mpg_championship_player_149035"},{"rating":5.5,"subId":"mpg_championship_player_512711","starterId":"mpg_championship_player_209171"},{"rating":5.5,"subId":"mpg_championship_player_509285","starterId":"mpg_championship_player_245485"},{"rating":5.5,"subId":"mpg_championship_player_437503","starterId":"mpg_championship_player_167454"},{"rating":5.5,"subId":"mpg_championship_player_454964","starterId":"mpg_championship_player_235708"}],"selectedBonus":{"name":"boostAllPlayers"}}
```

**WARNING**: Bonus name has change (was perhaps Id, don't remind exactly).
