### ISSUE TITLE
Players not found during Team creation

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#199]
Today on L1:

```bash
Exception in thread "main" java.lang.UnsupportedOperationException: Player with id 'mpg_championship_player_XXXX' cannot found
        at org.blondin.mpg.root.model.PoolPlayers.lambda$getPlayer$1(PoolPlayers.java:18)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.blondin.mpg.root.model.PoolPlayers.getPlayer(PoolPlayers.java:18)
        at org.blondin.mpg.Main.completePlayersTeam(Main.java:250)
        at org.blondin.mpg.Main.processGames(Main.java:175)
        at org.blondin.mpg.Main.processLeague(Main.java:114)
        at org.blondin.mpg.Main.process(Main.java:82)
        at org.blondin.mpg.Main.main(Main.java:71)
```

**Comment by axel3rd** [comment]
**Root Cause**: Some players (sample: Alexandre Lauray) doesn't exist no more in PoolPlayer (L1)
