### ISSUE TITLE
Captain bonus no more cumulative with UberEats (boostOnePlayer)

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#209]
Seems new (explicit in Captain bonus selection), provides:

```
Exception in thread "main" org.blondin.mpg.root.exception.UrlForbiddenException: Forbidden URL: https://api.mpg.football
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:147)
        at org.blondin.mpg.AbstractClient.put(AbstractClient.java:111)
```

**Comment by axel3rd** [comment]
Reopen because on PL today:

```
Updating team ...
  Captain: Trossard Leandro
  Bonus  : boostOnePlayer (Trossard Leandro)
Exception in thread "main" org.blondin.mpg.root.exception.UrlForbiddenException: Forbidden URL: https://api.mpg.football
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:147)
```
