### ISSUE TITLE
Bonus selection fails

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#246]
When no more bonus except "decat":

```
Updating team ...
Exception in thread "main" java.lang.UnsupportedOperationException: Bonus cannot be null here, bug in selection algorithm !
        at org.blondin.mpg.Main.getBestBonus(Main.java:641)
        at org.blondin.mpg.Main.selectBonus(Main.java:615)
        at org.blondin.mpg.Main.getCoachRequest(Main.java:524)
        at org.blondin.mpg.Main.updateTeamWithRetry(Main.java:276)
```

**Comment by axel3rd** [comment]
In fact, part of https://github.com/axel3rd/mpg-coach-bot/issues/234
