### ISSUE TITLE
MpgStatsClient.getStats - 404 Not Found / Content

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#268]
Error:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 404 Not Found / Content: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:159)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:100)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:92)
        at org.blondin.mpg.stats.MpgStatsClient.getStats(MpgStatsClient.java:41)
        at org.blondin.mpg.AbstractMpgProcess.getCurrentDay(AbstractMpgProcess.java:106)
        at org.blondin.mpg.AbstractMpgProcess.calculateEfficiencies(AbstractMpgProcess.java:86)
        at org.blondin.mpg.AbstractMpgProcess.completeAuctionAndcalculateEfficiency(AbstractMpgProcess.java:57)
        at org.blondin.mpg.Games.process(Games.java:56)
        at org.blondin.mpg.Main.processLeague(Main.java:79)
        at org.blondin.mpg.Main.process(Main.java:39)
        at org.blondin.mpg.Main.main(Main.java:28)
```

**Comment by axel3rd** [comment]
[MpgStatsClient.getStats(MpgStatsClient.java:41)](https://github.com/axel3rd/mpg-coach-bot/blob/cb0f8b98556a753ee0ae72d964983b2797d67363/src/main/java/org/blondin/mpg/stats/MpgStatsClient.java#L41) is an old request call on v1 endpoint ... doesn't exist anymore.

**Comment by axel3rd** [comment]
Clearly a lack in v2 enpoint implementation (https://github.com/axel3rd/mpg-coach-bot/issues/229).

**Comment by axel3rd** [comment]
That's why the Code Coverage is important ! 
https://sonarcloud.io/code?id=org.blondin%3Ampg-coach-bot&selected=org.blondin%3Ampg-coach-bot%3Asrc%2Fmain%2Fjava%2Forg%2Fblondin%2Fmpg%2Fstats%2FMpgStatsClient.java&line=41
