### ISSUE TITLE
Support transition status (preparation, end of season, terminated, ...)

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#39]
**Describe the bug**

When no more match are available in MPG season (*Plus de match disponible.* in **Coach** screen), this exception occurs:

```
========== League Name ==========
Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
        at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:321)
        at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:389)
        at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:264)
        at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:117)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:63)
        at org.blondin.mpg.root.MpgClient.getCoach(MpgClient.java:42)
        at org.blondin.mpg.Main.process(Main.java:48)
        at org.blondin.mpg.Main.main(Main.java:40)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Root name 'success' does not match expected ('data') for type [simple type, class org.blondin.mpg.root.model.Coach]
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@f9af83; line: 1, column: 2]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
        at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
        at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1693)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1580)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
        at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
        ... 14 more
```

A clear and concise description of what the bug is, with a copy/paste of Java exception if present.

**Join debug files**

The result of  `GET /league/[yourLeagueId]/coach` is (in this case):

```
{"success":"noMoreGames"}
```

**Expected behavior**

It should not crash, but normal exist with correct message.

**Comment by axel3rd** [comment]
In addition, all transition status should be supported.

For `user/dashboard` response is:

```
{"data":{"follow":[],"leagues":[{"id":"KX24XMUG","admin_mpg_user_id":"mpg_user_1520001","current_mpg_user":"mpg_user_955966","name":"Achille Needle","leagueStatus":1,"championship":1,"mode":1,"teamStatus":null,"url":"assets/public/img/league/10.jpg"},{"id":"KLGXSSUG","admin_mpg_user_id":"mpg_user_963519","current_mpg_user":"mpg_user_955966","name":"Rock on the grass","leagueStatus":5,"championship":1,"mode":2,"teamStatus":2,"url":"assets/public/img/league/3.jpg"}]}}
```

KX24XMUG : In creation : leagueStatus = 1
KLGXSSUG : Terminated : leagueStatus = 5
When championship in game : leagueStatus = 4

**Comment by axel3rd** [comment]
For `user/dashboard` response is:

```
{"data":{"follow":[],"leagues":[{"id":"KX24XMUG","admin_mpg_user_id":"mpg_user_1520001","current_mpg_user":"mpg_user_955966","name":"Achille Needle","leagueStatus":3,"championship":1,"mode":2,"teamStatus":null,"url":"assets/public/img/league/10.jpg"},{"id":"KLGXSSUG","admin_mpg_user_id":"mpg_user_963519","current_mpg_user":"mpg_user_955966","name":"Rock on the grass","leagueStatus":5,"championship":1,"mode":2,"teamStatus":2,"url":"assets/public/img/league/3.jpg"}]}}
```
When staus is 3 : Mercato

In this case `coach` throw exception : 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 401 Unauthorized
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:111)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:63)
        at org.blondin.mpg.root.MpgClient.getCoach(MpgClient.java:42)
        at org.blondin.mpg.Main.process(Main.java:48)
        at org.blondin.mpg.Main.main(Main.java:40)
```
