### ISSUE TITLE
Mercato suggest

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#40]
When league is in preparation (status 1, #39), suggest should be provided for mercato ; by line based on efficiency.

For cotation, `https://api.monpetitgazon.com/mercato/1` (for French championship)

**Comment by axel3rd** [comment]
For mercato start in league, url is:

    https://api.monpetitgazon.com/league/KXXidLeagueXX/mercato

**Comment by axel3rd** [comment]
When mercato is done (until next turn), error like:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 401 Unauthorized / Content: {"error":"notGoodStatus"}
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:117)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:69)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:57)
        at org.blondin.mpg.root.MpgClient.getMercato(MpgClient.java:77)
        at org.blondin.mpg.Main.processMercatoLeague(Main.java:77)
        at org.blondin.mpg.Main.process(Main.java:63)
        at org.blondin.mpg.Main.main(Main.java:51)
```
