### ISSUE TITLE
Update fail after weekend

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#69]
After the weekend, when team substitutes are reseted, the update fail with : 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 400 Bad Request / Content: {"error":"badRequest"}
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:124)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:85)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:81)
        at org.blondin.mpg.root.MpgClient.updateCoach(MpgClient.java:95)
        at org.blondin.mpg.Main.updateTeamWithRetry(Main.java:188)
        at org.blondin.mpg.Main.processGames(Main.java:164)
        at org.blondin.mpg.Main.processLeague(Main.java:90)
        at org.blondin.mpg.Main.process(Main.java:68)
        at org.blondin.mpg.Main.main(Main.java:59)
```

It is strange, because if you save you team on MPG as it is ... and execute *mpg-coach-bot* with update, it works.

**Comment by axel3rd** [comment]
After debugging with a REST client, the root cause seems about data: `"bonusSelected": null,`.
It should be `    "bonusSelected": {},` to work.

**Comment by axel3rd** [comment]
Explanation: After weekend, `null` is in response for *bonusSelected*, so reuse as it. Any update in UI remove this *null* value.
